/* BEGIN HEADER */
#ifndef example1_INCLUDE_
#define example1_INCLUDE_

#include <assert.h>
#include <unordered_map>
#include <utility>

#include "classp.h"

// Include files generated by bison
#include "example1.yacc.hh"
#include "location.hh"
#include "position.hh"

namespace example1 {
using std::istream;
using std::ostream;
using classp::classpPrint;
using classp::classpFormat;
using classp::AttributeMap;

// Location and state information from the parser.
typedef location ParseState;

class AstNode;
/* BEGIN FORWARD DECLARATIONS */
class Expression;
class FunctionCall;
/* END FORWARD DECLARATIONS */

// Base class for example1 AST nodes
class AstNode : public classp::ClasspNode {
 public:
  string className() override { return "AstNode"; }
  AstNode(ParseState parseState)
    : parseState(parseState) {
    }

  // Write out a bracketed form of this AST from the declared syntax.
  virtual void bracketFormat(std::ostream& out, AstNode* self) {
    assert(false);
  }

  ParseState parseState;
};

/* BEGIN CLASS DEFINITIONS */
class Expression: public AstNode {
 public:
  string className() override { return "Expression"; }
  Expression(ParseState parseState);
  static Expression* parse(istream& input, ostream& errors);
  void printMembers(ostream& out) override;

};

class FunctionCall: public Expression {
 public:
  string className() override { return "FunctionCall"; }
  FunctionCall(ParseState parseState, identifier functionName, vector<Expression*> argList);
  void printMembers(ostream& out) override;
  void format(ostream& out, int precedence) override;

  identifier functionName;
  vector<Expression*> argList;
};
/* END CLASS DEFINITIONS */

}  // namespace example1
#endif // example1_INCLUDE_

/* END HEADER */
