/* BEGIN HEADER */
#ifndef example2_INCLUDE_
#define example2_INCLUDE_

#include <assert.h>
#include <unordered_map>
#include <utility>

#include "classp.h"

// Include files generated by bison
#include "example2.yacc.hh"
#include "location.hh"
#include "position.hh"

namespace example2 {
using std::istream;
using std::ostream;
using classp::classpPrint;
using classp::classpFormat;
using classp::AttributeMap;

// Location and state information from the parser.
typedef location ParseState;

class AstNode;
/* BEGIN FORWARD DECLARATIONS */
class Expression;
class FunctionCall;
class IntegerLiteral;
class Product;
class Sum;
/* END FORWARD DECLARATIONS */

// Base class for example2 AST nodes
class AstNode : public classp::ClasspNode {
 public:
  string className() override { return "AstNode"; }
  AstNode(ParseState parseState)
    : parseState(parseState) {
    }

  // Write out a bracketed form of this AST from the declared syntax.
  virtual void bracketFormat(std::ostream& out, AstNode* self) {
    assert(false);
  }

  ParseState parseState;
};

/* BEGIN CLASS DEFINITIONS */
class Expression: public AstNode {
 public:
  string className() override { return "Expression"; }
  Expression(ParseState parseState);
  static Expression* parse(istream& input, ostream& errors);
  void printMembers(ostream& out) override;
  void bracketFormat(ostream& out, AstNode* self) override;

};

class FunctionCall: public Expression {
 public:
  string className() override { return "FunctionCall"; }
  FunctionCall(ParseState parseState, identifier functionName, vector<Expression*> argList);
  void printMembers(ostream& out) override;
  void format(ostream& out, int precedence) override;

  identifier functionName;
  vector<Expression*> argList;
};

class Sum: public Expression {
 public:
  string className() override { return "Sum"; }
  Sum(ParseState parseState, Expression* val1, Expression* val2);
  void printMembers(ostream& out) override;
  void format(ostream& out, int precedence) override;

  Expression* val1 = nullptr;
  Expression* val2 = nullptr;
};

class Product: public Expression {
 public:
  string className() override { return "Product"; }
  Product(ParseState parseState, Expression* val1, Expression* val2);
  void printMembers(ostream& out) override;
  void format(ostream& out, int precedence) override;

  Expression* val1 = nullptr;
  Expression* val2 = nullptr;
};

class IntegerLiteral: public Expression {
 public:
  string className() override { return "IntegerLiteral"; }
  IntegerLiteral(ParseState parseState, int val);
  void printMembers(ostream& out) override;
  void format(ostream& out, int precedence) override;

  int val;
};
/* END CLASS DEFINITIONS */

}  // namespace example2
#endif // example2_INCLUDE_

/* END HEADER */
