/* BEGIN HEADER */
#ifndef t1_INCLUDE_
#define t1_INCLUDE_

#include <assert.h>
#include <unordered_map>
#include <utility>

#include "classp.h"

// Include files generated by bison
#include "t1.yacc.hh"
#include "location.hh"
#include "position.hh"

namespace t1 {
using std::istream;
using std::ostream;
using classp::classpPrint;
using classp::classpFormat;
using classp::AttributeMap;

// Location and state information from the parser.
typedef location ParseState;

class AstNode;
/* BEGIN FORWARD DECLARATIONS */
class A;
class B;
class C;
class D;
/* END FORWARD DECLARATIONS */

// Base class for t1 AST nodes
class AstNode : public classp::ClasspNode {
 public:
  string className() override { return "AstNode"; }
  AstNode(ParseState parseState)
    : parseState(parseState) {
    }

  // Write out a bracketed form of this AST from the declared syntax.
  virtual void bracketFormat(std::ostream& out, AstNode* self) {
    assert(false);
  }

  ParseState parseState;
};

/* BEGIN CLASS DEFINITIONS */
class A: public AstNode {
 public:
  string className() override { return "A"; }
  A(ParseState parseState, AttributeMap& keyword_args);
  void printMembers(ostream& out) override;

  int x;
  bool has_x = false;
};

class B: public A {
 public:
  string className() override { return "B"; }
  B(ParseState parseState, AttributeMap& keyword_args);
  void printMembers(ostream& out) override;
  void format(ostream& out, int precedence) override;

  int y;
  bool has_y = false;
};

class C: public A {
 public:
  string className() override { return "C"; }
  C(ParseState parseState, AttributeMap& keyword_args);
  void printMembers(ostream& out) override;
  void format(ostream& out, int precedence) override;

  int z;
  bool has_z = false;
};

class D: public AstNode {
 public:
  string className() override { return "D"; }
  D(ParseState parseState, A* a, B* b, C* c);
  static D* parse(istream& input, ostream& errors);
  void printMembers(ostream& out) override;
  void format(ostream& out, int precedence) override;

  A* a = nullptr;
  B* b = nullptr;
  C* c = nullptr;
};
/* END CLASS DEFINITIONS */

}  // namespace t1
#endif // t1_INCLUDE_

/* END HEADER */
